version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:80"   # A API ficará acessível em http://localhost:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # O site ficará acessível em http://localhost:3000
